name: "Get & Cache Dependencies"
description: "Action to get and cache dependencies (via npm) for a Node.js project"
inputs:
  caching:
    description: "Whether to cache dependencies or not"
    required: false
    default: "true"
outputs:
  cache-hit:
    description: "Whether or not the cache was used"
    value: ${{steps.cache.install-dependencies.cache-hit-output}}
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      id: cache
      if: ${{ inputs.caching == 'true' }}
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install-dependencies
      if: steps.cache.outputs.cache-hit != 'true' || '${{ inputs.caching != true' }}'
      run: |
        npm ci
        echo "cache-hit-output='${{ inputs.caching }}'"">>$GITHUB_OUTPUT
      shell: bash
